"""The seminal-paper canon for the portal's Classics -> "Seminal by topic" view.

A hand-curated map of {topic: [papers]}, where each paper is
(title, author_hint, year, type, why):

  title       exact-ish paper title (used to resolve the real record on OpenAlex)
  author_hint a surname to disambiguate the OpenAlex match (not displayed)
  year        publication year (canonical; verified against the resolved record)
  type        "Theory" | "Method" | "Empirical" | "Frontier"
              -- the paper's primary contribution ("Frontier" = an emerging idea
                 that matters regardless of citation count)
  why         one line on why it mattered (<= ~100 chars)

backfill.py resolves each entry to its OpenAlex record for the citation count,
authors, journal, and link -- so the *judgment* here is curated but every fact
shown is grounded in a real record. Citations are shown as metadata only: the
canon is a curated record of seminal IDEAS, never filtered or ranked by cite
count, so lightly-cited frontier work sits beside the classics on merit. Edit
freely: add/remove papers or topics and re-run `python backfill.py`. Topics are
ordered as they should appear; papers are re-sorted chronologically at render.
"""

CANON: dict[str, list[tuple]] = {
    "Asset Pricing Theory": [
        ("Portfolio Selection", "Markowitz", 1952, "Theory",
         "Mean-variance framework; risk as return variance and the efficient frontier."),
        ("Capital Asset Prices: A Theory of Market Equilibrium under Conditions of Risk", "Sharpe", 1964, "Theory",
         "The CAPM: expected return is linear in market beta."),
        ("The Valuation of Risk Assets and the Selection of Risky Investments in Stock Portfolios and Capital Budgets", "Lintner", 1965, "Theory",
         "Independent derivation of the CAPM equilibrium."),
        ("An Intertemporal Capital Asset Pricing Model", "Merton", 1973, "Theory",
         "ICAPM: hedging demands against shifting investment opportunities."),
        ("The Arbitrage Theory of Capital Asset Pricing", "Ross", 1976, "Theory",
         "APT: returns driven by multiple priced factors, from no-arbitrage."),
        ("Asset Prices in an Exchange Economy", "Lucas", 1978, "Theory",
         "Consumption-based pricing: assets priced by the marginal utility of consumption."),
        ("An Intertemporal Asset Pricing Model with Stochastic Consumption and Investment Opportunities", "Breeden", 1979, "Theory",
         "The consumption-CAPM in continuous time."),
        ("The Equity Premium: A Puzzle", "Mehra", 1985, "Empirical",
         "Historical equity premium far exceeds what standard models justify."),
        ("Implications of Security Market Data for Models of Dynamic Economies", "Hansen", 1991, "Method",
         "Hansen-Jagannathan bounds on the pricing kernel from asset data."),
        ("By Force of Habit: A Consumption-Based Explanation of Aggregate Stock Market Behavior", "Campbell", 1999, "Theory",
         "Habit formation generates time-varying risk premia."),
        ("Risks for the Long Run: A Potential Resolution of Asset Pricing Puzzles", "Bansal", 2004, "Theory",
         "Long-run consumption risk explains the premium and its dynamics."),
    ],
    "Factor Models & the Cross-Section": [
        ("Risk, Return, and Equilibrium: Empirical Tests", "Fama", 1973, "Method",
         "Fama-MacBeth cross-sectional regressions for testing risk premia."),
        ("The Relationship Between Return and Market Value of Common Stocks", "Banz", 1981, "Empirical",
         "The size effect: small caps earn higher risk-adjusted returns."),
        ("Returns to Buying Winners and Selling Losers: Implications for Stock Market Efficiency", "Jegadeesh", 1993, "Empirical",
         "Momentum: past winners keep beating past losers at 3-12 months."),
        ("The Cross-Section of Expected Stock Returns", "Fama", 1992, "Empirical",
         "Size and book-to-market dominate beta in explaining returns."),
        ("Common Risk Factors in the Returns on Stocks and Bonds", "Fama", 1993, "Method",
         "The three-factor model (market, size, value) -- the empirical workhorse."),
        ("On Persistence in Mutual Fund Performance", "Carhart", 1997, "Empirical",
         "Adds momentum to form the four-factor model."),
        ("The Other Side of Value: The Gross Profitability Premium", "Novy-Marx", 2013, "Empirical",
         "Profitability is a robust return predictor alongside value."),
        ("A Five-Factor Asset Pricing Model", "Fama", 2015, "Empirical",
         "Adds profitability and investment to the three-factor model."),
        ("Digesting Anomalies: An Investment Approach", "Hou", 2015, "Empirical",
         "The q-factor model prices many anomalies with investment and ROE."),
        ("... and the Cross-Section of Expected Returns", "Harvey", 2016, "Method",
         "Multiple-testing critique: most 'factors' fail a proper t-hurdle."),
    ],
    "Portfolio Construction & Optimization": [
        ("A New Interpretation of Information Rate", "Kelly", 1956, "Method",
         "The Kelly criterion: log-optimal growth bet sizing."),
        ("Lifetime Portfolio Selection under Uncertainty: The Continuous-Time Case", "Merton", 1969, "Theory",
         "Dynamic optimal allocation; foundation of continuous-time finance."),
        ("Bayes-Stein Estimation for Portfolio Analysis", "Jorion", 1986, "Method",
         "Shrinking expected-return estimates to tame optimizer error."),
        ("The Markowitz Optimization Enigma: Is Optimized Optimal?", "Michaud", 1989, "Method",
         "Names the estimation-error problem: optimizers maximize error."),
        ("Global Portfolio Optimization", "Black", 1992, "Method",
         "Black-Litterman: blend equilibrium priors with investor views."),
        ("Honey, I Shrunk the Sample Covariance Matrix", "Ledoit", 2004, "Method",
         "Shrinkage covariance estimation for stable large portfolios."),
        ("The Properties of Equally Weighted Risk Contribution Portfolios", "Maillard", 2010, "Method",
         "Formalizes risk parity: equalize each asset's risk contribution."),
        ("Optimal Versus Naive Diversification: How Inefficient Is the 1/N Portfolio Strategy?", "DeMiguel", 2009, "Empirical",
         "Out of sample, 1/N often beats optimized allocations."),
        ("Vive la Difference: Bayesian Analysis of Structural Differences between Portfolios", "Pastor", 2000, "Method",
         "Bayesian allocation embedding beliefs about model mispricing."),
    ],
    "Market Efficiency & Behavioral": [
        ("Proof that Properly Anticipated Prices Fluctuate Randomly", "Samuelson", 1965, "Theory",
         "Why efficient prices should look like a random walk."),
        ("Efficient Capital Markets: A Review of Theory and Empirical Work", "Fama", 1970, "Theory",
         "Defines weak/semi-strong/strong market efficiency."),
        ("Prospect Theory: An Analysis of Decision under Risk", "Kahneman", 1979, "Theory",
         "Loss aversion and probability weighting; root of behavioral finance."),
        ("On the Impossibility of Informationally Efficient Markets", "Grossman", 1980, "Theory",
         "If prices reveal all information, no one is paid to gather it."),
        ("Do Stock Prices Move Too Much to be Justified by Subsequent Changes in Dividends?", "Shiller", 1981, "Empirical",
         "Excess volatility: prices swing far more than fundamentals."),
        ("Noise Trader Risk in Financial Markets", "De Long", 1990, "Theory",
         "Irrational traders can persist and move prices."),
        ("The Limits of Arbitrage", "Shleifer", 1997, "Theory",
         "Why smart money can't always correct mispricing."),
        ("A Model of Investor Sentiment", "Barberis", 1998, "Theory",
         "Under- and over-reaction from investor psychology."),
        ("The Adaptive Markets Hypothesis", "Lo", 2004, "Theory",
         "Efficiency as evolving with market ecology, not absolute."),
    ],
    "Derivatives & Option Pricing": [
        ("The Pricing of Options and Corporate Liabilities", "Black", 1973, "Theory",
         "Black-Scholes: closed-form option pricing by replication."),
        ("Theory of Rational Option Pricing", "Merton", 1973, "Theory",
         "Extends and rigorizes option pricing; Merton bounds."),
        ("Option Pricing: A Simplified Approach", "Cox", 1979, "Method",
         "The binomial tree -- intuitive, flexible numerical pricing."),
        ("Martingales and Arbitrage in Multiperiod Securities Markets", "Harrison", 1979, "Theory",
         "Risk-neutral pricing via equivalent martingale measures."),
        ("A Closed-Form Solution for Options with Stochastic Volatility with Applications to Bond and Currency Options", "Heston", 1993, "Method",
         "The Heston model: analytic stochastic-volatility option prices."),
        ("Pricing with a Smile", "Dupire", 1994, "Method",
         "Local volatility surface consistent with quoted option prices."),
        ("Option Valuation Using the Fast Fourier Transform", "Carr", 1999, "Method",
         "FFT pricing for models with known characteristic functions."),
        ("Transform Analysis and Asset Pricing for Affine Jump-Diffusions", "Duffie", 2000, "Method",
         "General transform pricing for the affine model class."),
        ("Empirical Performance of Alternative Option Pricing Models", "Bakshi", 1997, "Empirical",
         "Benchmarks stochastic-vol and jump models against data."),
    ],
    "Volatility Modeling": [
        ("Autoregressive Conditional Heteroscedasticity with Estimates of the Variance of United Kingdom Inflation", "Engle", 1982, "Method",
         "ARCH: models time-varying, clustering volatility."),
        ("Generalized Autoregressive Conditional Heteroskedasticity", "Bollerslev", 1986, "Method",
         "GARCH: the parsimonious volatility workhorse."),
        ("Conditional Heteroskedasticity in Asset Returns: A New Approach", "Nelson", 1991, "Method",
         "EGARCH captures the asymmetric leverage effect."),
        ("Modeling and Forecasting Realized Volatility", "Andersen", 2003, "Method",
         "Realized volatility from high-frequency returns."),
        ("Econometric Analysis of Realized Volatility and Its Use in Estimating Stochastic Volatility Models", "Barndorff-Nielsen", 2002, "Theory",
         "Theory of realized variance as a volatility estimator."),
        ("Stock Return Characteristics, Skew Laws, and the Differential Pricing of Individual Equity Options", "Bakshi", 2003, "Empirical",
         "Model-free extraction of risk-neutral moments from options."),
        ("Variance Risk Premiums", "Carr", 2009, "Empirical",
         "Documents and prices the variance risk premium via swaps."),
        ("Expected Stock Returns and Variance Risk Premia", "Bollerslev", 2009, "Empirical",
         "The variance risk premium predicts aggregate returns."),
    ],
    "Fixed Income & Credit": [
        ("An Equilibrium Characterization of the Term Structure", "Vasicek", 1977, "Theory",
         "First equilibrium short-rate model of the yield curve."),
        ("On the Pricing of Corporate Debt: The Risk Structure of Interest Rates", "Merton", 1974, "Theory",
         "Structural credit risk: equity as an option on firm assets."),
        ("A Theory of the Term Structure of Interest Rates", "Cox", 1985, "Theory",
         "The CIR model: square-root, non-negative short rates."),
        ("Parsimonious Modeling of Yield Curves", "Nelson", 1987, "Method",
         "Nelson-Siegel: a low-parameter yield-curve fit."),
        ("Bond Pricing and the Term Structure of Interest Rates: A New Methodology for Contingent Claims Valuation", "Heath", 1992, "Theory",
         "HJM: arbitrage-free modeling of the whole forward curve."),
        ("Modeling Term Structures of Defaultable Bonds", "Duffie", 1999, "Method",
         "Reduced-form intensity-based default modeling."),
        ("Valuing American Options by Simulation: A Simple Least-Squares Approach", "Longstaff", 2001, "Method",
         "Least-squares Monte Carlo for early-exercise claims."),
    ],
    "Market Microstructure & Liquidity": [
        ("Continuous Auctions and Insider Trading", "Kyle", 1985, "Theory",
         "Kyle's lambda: how informed trading moves prices."),
        ("Bid, Ask and Transaction Prices in a Specialist Market with Heterogeneously Informed Traders", "Glosten", 1985, "Theory",
         "Spreads arise from adverse selection."),
        ("A Simple Implicit Measure of the Effective Bid-Ask Spread in an Efficient Market", "Roll", 1984, "Method",
         "Estimates the spread from return autocovariance."),
        ("Asset Pricing and the Bid-Ask Spread", "Amihud", 1986, "Theory",
         "Illiquidity is priced: investors demand a spread premium."),
        ("Illiquidity and Stock Returns: Cross-Section and Time-Series Effects", "Amihud", 2002, "Empirical",
         "The Amihud illiquidity measure predicts returns."),
        ("Liquidity Risk and Expected Stock Returns", "Pastor", 2003, "Empirical",
         "Systematic liquidity is a priced risk factor."),
        ("Measuring the Information Content of Stock Trades", "Hasbrouck", 1991, "Method",
         "VAR decomposition of the price impact of trades."),
        ("Optimal Execution of Portfolio Transactions", "Almgren", 2001, "Method",
         "Trade scheduling under the impact-vs-risk tradeoff."),
    ],
    "Fund Performance & Institutional": [
        ("Mutual Fund Performance", "Sharpe", 1966, "Method",
         "Introduces the reward-to-variability (Sharpe) ratio."),
        ("The Performance of Mutual Funds in the Period 1945-1964", "Jensen", 1968, "Method",
         "Jensen's alpha: risk-adjusted manager skill."),
        ("Another Puzzle: The Growth in Actively Managed Mutual Funds", "Gruber", 1996, "Empirical",
         "Why investors buy active funds that underperform."),
        ("The Risk in Hedge Fund Strategies: Theory and Evidence from Trend Followers", "Fung", 2001, "Empirical",
         "Hedge-fund returns as option-like (lookback straddle) exposures."),
        ("Mutual Fund Flows and Performance in Rational Markets", "Berk", 2004, "Theory",
         "Skill is competed away by fund flows; alpha need not persist."),
        ("Hedge Fund Benchmarks: A Risk-Based Approach", "Fung", 2004, "Method",
         "Seven-factor risk model for hedge-fund returns."),
        ("Luck versus Skill in the Cross-Section of Mutual Fund Returns", "Fama", 2010, "Empirical",
         "Bootstrap shows few managers beat their costs."),
    ],
    "Machine Learning in Finance": [
        ("When Is a Liability Not a Liability? Textual Analysis, Dictionaries, and 10-Ks", "Loughran", 2011, "Method",
         "Finance-specific sentiment dictionaries for textual analysis."),
        ("Pseudo-Mathematics and Financial Charlatanism: The Effects of Backtest Overfitting on Out-of-Sample Performance", "Bailey", 2014, "Method",
         "Quantifies how multiple backtesting inflates false discoveries."),
        ("Characteristics Are Covariances: A Unified Model of Risk and Return", "Kelly", 2019, "Method",
         "IPCA: latent factors with characteristic-driven loadings."),
        ("Empirical Asset Pricing via Machine Learning", "Gu", 2020, "Empirical",
         "Trees and neural nets sharply improve return prediction."),
        ("Taming the Factor Zoo: A Test of New Factors", "Feng", 2020, "Method",
         "Model-selection (LASSO) test for whether a new factor adds."),
        ("Shrinking the Cross-Section", "Kozak", 2020, "Method",
         "A robust SDF from many characteristics via shrinkage."),
        ("Dissecting Characteristics Nonparametrically", "Freyberger", 2020, "Method",
         "Nonparametric selection of which characteristics matter."),
        ("Deep Learning in Asset Pricing", "Chen", 2024, "Method",
         "A no-arbitrage neural SDF conditioned on macro states."),
        ("Autoencoder Asset Pricing Models", "Gu", 2021, "Method",
         "Conditional autoencoder: latent factors with characteristic betas."),
        ("Temporal Relational Ranking for Stock Prediction", "Feng", 2019, "Frontier",
         "Relational stock ranking over a graph of firm relations (graph + temporal)."),
        ("Modeling the Stock Relation with Graph Network for Overnight Stock Movement Prediction", "Li", 2020, "Frontier",
         "Graph network propagating information across related stocks."),
        ("Financial Time Series Forecasting with Multi-Modality Graph Neural Network", "Cheng", 2022, "Frontier",
         "Multi-modal GNN fusing price, relation, and event graphs."),
    ],
    "Financial Econometrics": [
        ("Distribution of the Estimators for Autoregressive Time Series with a Unit Root", "Dickey", 1979, "Method",
         "The Dickey-Fuller test for non-stationarity."),
        ("A Heteroskedasticity-Consistent Covariance Matrix Estimator and a Direct Test for Heteroskedasticity", "White", 1980, "Method",
         "White standard errors robust to heteroskedasticity."),
        ("Large Sample Properties of Generalized Method of Moments Estimators", "Hansen", 1982, "Method",
         "GMM: estimation from moment conditions, ubiquitous in finance."),
        ("A Simple, Positive Semi-Definite, Heteroskedasticity and Autocorrelation Consistent Covariance Matrix", "Newey", 1987, "Method",
         "Newey-West HAC standard errors."),
        ("Co-integration and Error Correction: Representation, Estimation, and Testing", "Engle", 1987, "Method",
         "Cointegration -- the basis of pairs trading and long-run links."),
        ("Comparing Predictive Accuracy", "Diebold", 1995, "Method",
         "The Diebold-Mariano test for forecast comparison."),
    ],
}
