#!/usr/bin/env python3
"""Write docs/CLASSICS.md -- a readable index of the curated classics.

Generated from the archive rather than hand-maintained, so it stays in step
with ingest and full-text runs. Marks which papers have GROBID passages, since
that is what decides whether Ask can quote a paper or only cite it.

  python tools/classics_md.py
"""

import collections
import glob
import json
import os
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

import store  # noqa: E402

OUT = pathlib.Path("docs/CLASSICS.md")


def safe(uid):
    return "".join(c if c.isalnum() or c in "._-" else "_" for c in uid)[:120]


def main():
    con = store.connect()
    ft = {os.path.basename(f)[:-5]
          for f in glob.glob("docs/ft/*.json") if not f.endswith("index.json")}

    canon, cited = collections.defaultdict(list), []
    for uid, title, meta in con.execute("SELECT uid, title, meta FROM items"):
        try:
            d = json.loads(meta)
        except Exception:                                   # noqa: BLE001
            continue
        if not d.get("classic"):
            continue
        row = {
            "title": (title or "").strip(),
            "authors": (d.get("authors") or "").strip(),
            "year": (d.get("date") or "")[:4],
            "journal": (d.get("journal") or "").strip(),
            "cites": d.get("cites"),
            "url": d.get("url") or (f"https://doi.org/{d['doi']}"
                                    if d.get("doi") else ""),
            "full": safe(uid) in ft,
            "why": (d.get("canon_why") or "").strip(),
            "type": d.get("canon_type", ""),
        }
        if d.get("source") == "classic:canon":
            canon[d.get("canon_topic", "Other")].append(row)
        else:
            cited.append(row)

    n_all = sum(len(v) for v in canon.values()) + len(cited)
    n_full = sum(1 for v in canon.values() for r in v if r["full"]) \
        + sum(1 for r in cited if r["full"])

    L = ["# Classics", "",
         "The curated foundation of the archive: the seminal canon plus the "
         "most-cited papers in the field. These are ingested as ordinary "
         "archive items, so Ask can retrieve and cite them alongside current "
         "work.", "",
         f"**{n_all} papers** · **{n_full}** with full text parsed "
         f"(the rest are citable from their abstract, not quotable).", "",
         "Generated by `tools/classics_md.py` — regenerate after an ingest or "
         "a full-text run.", "", "---", ""]

    def fmt(r):
        bits = [f"**{r['title']}**"]
        meta = " · ".join(x for x in (r["authors"][:70], r["year"],
                                      r["journal"][:40]) if x)
        line = f"- {bits[0]}"
        if meta:
            line += f"  \n  {meta}"
        tags = []
        if r["full"]:
            tags.append("full text")
        if r["cites"]:
            tags.append(f"{r['cites']:,} cites")
        if r["type"]:
            tags.append(r["type"].lower())
        if tags:
            line += f"  \n  _{' · '.join(tags)}_"
        if r["url"]:
            line += f" — [link]({r['url']})"
        if r["why"]:
            line += f"  \n  {r['why']}"
        return line

    L += ["## Seminal canon", "",
          "Hand-curated, grouped by topic. The one-line note is the reason "
          "each earns its place.", ""]
    for topic in sorted(canon):
        rows = sorted(canon[topic], key=lambda r: r["year"] or "")
        L += [f"### {topic} ({len(rows)})", ""]
        L += [fmt(r) for r in rows]
        L.append("")

    L += ["---", "", f"## Most-cited ({len(cited)})", "",
          "Ranked by citation count.", ""]
    for r in sorted(cited, key=lambda r: -(r["cites"] or 0))[:400]:
        L.append(fmt(r))

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT} — {n_all} papers, {n_full} with full text, "
          f"{OUT.stat().st_size/1000:.0f} KB")


if __name__ == "__main__":
    main()
